#
#  Configuration for docker-rpi-nodejs-gpio
#
gulp:
  start:
    development:
      gulp:
        - 'lint'
        - 'build'
        - 'watch'
        - 'gpio-stop'
        - 'gpio-start'
        - 'livereload-start'
        - 'server-start'
        - 'tests'
        - 'livereload'
#        - 'livereload-all'
      build:
        - 'less'
        - 'js'
        - 'locales'
#        - 'jsdoc'
      tests:
        - 'test-modules'
      lint:
        - 'ejslint'
        - 'eslint'
        - 'jsonlint'
        - 'yamllint'
        - 'puglint'
        - 'ejslint'
      server:
        - 'gpio-stop'
        - 'gpio-start'
        - 'server-changed'
        - 'tests'
    staging:
      gulp:
        - 'watch'
        - 'server-start'
      build: []
      tests: []
      lint: []
      server:
        - 'server-changed'
      watch:
        - 'server'
    production:
      gulp:
        - 'build'
        - 'gpio-stop'
        - 'gpio-start'
        - 'server-start'
      build:
        - 'less'
        - 'js'
        - 'locales'
      tests: []
      lint: []
      server:
        - 'server-changed'
  watch:
    eslint:
      - '*.js'
      - '.eslintrc.js'
      - 'gpio/**/*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'modules/**/*.js'
    js:
      - 'modules/*/js/*.js'
    jsdoc:
#      - 'nofile.js'
      - '*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'modules/**/*.js'
    jsonlint:
      - '**/*.json'
      - '.lesshintrc'
      - '!src/locales/*.json'
      - '!modules/**/locales/*.json'
    locales:
      - 'src/locales/*.json'
      - 'modules/**/locales/*.json'
    yamllint:
      - '**/*.yaml'
      - '**/*.yml'
    ejslint-livereload:
      - '**/*.ejs'
    less:
      - 'src/less/**/*.less'
      - 'modules/**/*.less'
    puglint:
      - '**/*.pug'
    server:
      - 'server.js'
      - 'gpio/**/*.js'
      - 'modules/**/!(tests)/server/*.js'
    livereload:
      - 'public/**/*.html'
      - 'public/img/**/*.*'
      - 'generated/**/*.css'
      - 'modules/**/*.ejs'
      - 'modules/**/*.pug'
    livereload-all:
      - 'generated/**/*.js'
      - 'locales/**/*.*'
    test-modules:
      - 'modules/**/tests/model/*.*'
      - 'modules/**/tests/server/*.*'
      - 'modules/**/views/**/*.*'
      - 'htdocs/js/**/*.js'
  tests:
    modules:
      - 'modules/**/tests/model/*.js'
      - 'modules/**/tests/server/*.js'
      - 'modules/**/tests/views/*.js'
  build:
    jsdoc:
      src:
        - '*.js'
        - 'gpio/**/*.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'modules/**/*.js'
        - 'src/**/*.js'
      dest: 'docs/jsdoc'
    js:
      src:
        - 'modules/*/js/*.js'
      dest: 'generated'
      replace:
        'modules/(.+/)js/.+': '$1'
    less:
      src:
        - 'src/less/app.less'
        - 'modules/*/less/layout.less'
      dest: 'generated'
    locales:
      dest: 'locales'
    deploy:
      src:
        - 'CHANGELOG.md'
        - 'configuration.yaml'
        - 'Dockerfile'
        - 'LICENSE'
        - 'package.json'
        - 'README.md'
        - 'server.js'
        - 'generated/*'
        - 'lib/**/*'
        - 'locales/*'
        - 'modules/*/*.json'
        - 'modules/*/*.yaml'
        - 'modules/*/server/**/*'
        - 'modules/*/views/**/*'
        - 'public/**/*'
      dest: 'deploy'

gpio:
  LED:
    'LED 1':
      type: 'LED'
      gpio: 27
      color: 'red'
      range: { min: 1, max: 255 }
    'LED 2':
      type: 'LED'
      gpio: 17
      color: 'yellow'
      range: { min: 1, max: 255 }
    'LED 3':
      type: 'LED'
      gpio: 22
      color: 'green'
      range: { min: 1, max: 51 }
    'LED 4':
      type: 'LED'
      gpio: 10
      color: 'blue'
      range: { min: 1, max: 255 }
  'RGB LED':
    'RGB LED 1':
      type: 'RGBLED'
      gpio: { red: 23, green: 24, blue: 25 }
    'RGB LED 2':
      type: 'RGBLED'
      gpio: { red: 26, green: 19, blue: 13 }
    'RGB LED 3':
      type: 'RGBLED'
      gpio: { red: 21, green: 20, blue: 16 }
  Servo:
    'Servo 1':
      type: 'Servo'
      gpio: 18
  Button:
    'Button 1':
      type: 'Button'
      gpio: 7
  Sensor:
    'Sensor 1':
      type: 'Sensor'
      gpio: 8

server:
  server: ./server.js
  docroot: ./public
  generated: ./generated
  modules: ./modules
  verbose: false
  httpsKey: ./key/selfsigned.key
  httpsCert: ./key/selfsigned.crt
