#
#  Configuration for docker-rpi-nodejs-gpio
#

gulp:
  watch:
    js:
      - 'src/js/*.js'
    jsdoc:
#      - '*.js'
#      - 'gulp/**/*.js'
#      - 'lib/**/*.js'
      - 'src/**/*.js'
    jshint:
      - '*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'src/**/*.js'
    jsonlint:
      - '**/*.json'
      - '.jscsrc'
      - '.jshintrc'
      - '.lesshintrc'
    lesshint:
      - 'src/less/**/*.less'
    yamllint:
      - '**/*.yaml'
      - '**/*.yml'
    ejslint:
      - '**/*.ejs'
    puglint:
      - '**/*.pug'
    less:
      - 'src/less/gpio.less'
      - 'src/less/**/*.less'
    server-restart:
      - './server.js'
    gpio-restart:
      - './gpio.js'
    livereload:
      - 'public/**/*.html'
      - 'public/css/gpio.css'
      - 'public/js/**/*.js'
  build:
    jsdoc:
      src:
        - '*.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'modules/**/*.js'
        - 'src/**/*.js'
      dest: 'docs/jsdoc'
    js:
      src: 'src/js/*.js'
      dest: 'public/js'
      replace:
        '/js': ''
    less:
      src: 'src/less/gpio.less'
      dest: 'public/css'

gpio:
  'LEDs':
    'LED 1':
      type: 'Led'
      gpio: 17
      color: 'red'
      range: { min: 1, max: 255 }
    'LED 2':
      type: 'Led'
      gpio: 27
      color: 'yellow'
      range: { min: 1, max: 255 }
    'LED 3':
      type: 'Led'
      gpio: 22
      color: 'green'
      range: { min: 1, max: 51 }
    'LED 4':
      type: 'Led'
      gpio: 10
      color: 'blue'
      range: { min: 1, max: 255 }
  'RGB LEDs':
    'RGB LED 1':
      type: 'RGBLed'
      gpio: { red: 23, green: 24, blue: 25 }
    'RGB LED 2':
      type: 'RGBLed'
      gpio: { red: 21, green: 20, blue: 16 }
    'RGB LED 3':
      type: 'RGBLed'
      gpio: { red: 26, green: 19, blue: 13 }
  Servo:
    'Servo 1':
      type: 'Servo'
      gpio: 18
  Button:
    'Button 1':
      type: 'Button'
      gpio: 7
  Sensor:
    'Sensor 1':
      type: 'Sensor'
      gpio: 8

server:
  server: './server.js'
  docroot: ./public
  httpPort: 8080
  livereloadPort: 8081
  verbose: false
