#
#  Configuration for docker-rpi-nodejs-gpio
#
gulp:
  start:
    development:
      gulp:
        - 'lint'
        - 'build'
        - 'watch'
        - 'gpio-stop'
        - 'gpio-start'
        - 'livereload-start'
        - 'server-start'
        - 'tests'
      build:
        - 'less'
        - 'js'
#        - 'jsdoc'
      tests:
        - 'test-modules'
      lint:
        - 'ejslint'
        - 'eslint'
        - 'jsonlint'
        - 'yamllint'
        - 'puglint'
        - 'ejslint'
      server:
        - 'gpio-stop'
        - 'gpio-start'
        - 'server-changed'
        - 'tests'
    production:
      gulp:
        - 'build'
        - 'gpio-stop'
        - 'gpio-start'
        - 'server-start'
      build:
        - 'less'
        - 'js'
      tests: []
      lint: []
      server:
        - 'server-changed'
  watch:
    eslint:
      - '*.js'
      - '.eslintrc.js'
      - 'gpio/**/*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'modules/**/*.js'
    js:
      - 'modules/*/js/*.js'
    jsdoc:
      - 'nofile.js'
    jsonlint:
      - '**/*.json'
      - '.lesshintrc'
    yamllint:
      - '**/*.yaml'
      - '**/*.yml'
    ejslint-livereload:
      - '**/*.ejs'
    less:
      - 'src/less/**/*.less'
      - 'modules/**/*.less'
    puglint:
      - '**/*.pug'
    server:
      - 'server.js'
      - 'gpio/**/*.js'
      - 'modules/**/!(tests)/server/*.js'
    livereload:
      - 'public/**/*.html'
      - 'modules/**/*.pug'
      - 'public/img/**/*.*'
      - 'public/css/*.css'
    livereload-index:
      - 'public/js/**/*.js'
    test-modules:
      - 'modules/**/tests/model/*.*'
      - 'modules/**/tests/server/*.*'
      - 'modules/**/views/**/*.*'
      - 'htdocs/css/*.css'
      - 'htdocs/js/**/*.js'
  tests:
    modules:
      - 'modules/**/tests/model/*.js'
      - 'modules/**/tests/server/*.js'
      - 'modules/**/tests/views/*.js'
  build:
    jsdoc:
      src:
        - '*.js'
        - 'gpio/**/*.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'modules/**/*.js'
        - 'src/**/*.js'
      dest: 'docs/jsdoc'
    js:
      src:
        - 'modules/*/js/*.js'
      dest: 'public/js'
      replace:
        'modules/([^/]+)/js(/[^/]+)?/.+': '$1$2'
    less:
      src: 'src/less/app.less'
      dest: 'public/css'

gpio:
  LED:
    'LED 1':
      type: 'LED'
      gpio: 27
      color: 'red'
      range: { min: 1, max: 255 }
    'LED 2':
      type: 'LED'
      gpio: 17
      color: 'yellow'
      range: { min: 1, max: 255 }
    'LED 3':
      type: 'LED'
      gpio: 22
      color: 'green'
      range: { min: 1, max: 51 }
    'LED 4':
      type: 'LED'
      gpio: 10
      color: 'blue'
      range: { min: 1, max: 255 }
  'RGB LED':
    'RGB LED 1':
      type: 'RGBLED'
      gpio: { red: 23, green: 24, blue: 25 }
    'RGB LED 2':
      type: 'RGBLED'
      gpio: { red: 26, green: 19, blue: 13 }
    'RGB LED 3':
      type: 'RGBLED'
      gpio: { red: 21, green: 20, blue: 16 }
  Servo:
    'Servo 1':
      type: 'Servo'
      gpio: 18
  Button:
    'Button 1':
      type: 'Button'
      gpio: 7
  Sensor:
    'Sensor 1':
      type: 'Sensor'
      gpio: 8

server:
  server: ./server.js
  docroot: ./public
  modules: ./modules
  httpPort: 8080
  livereloadPort: 8081
  socketPort: 8082
  verbose: false
